# Generated by Django 2.2 on 2020-07-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20200725_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
