# Generated by Django 2.2 on 2020-07-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_tripmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripManager',
        ),
    ]
