# Generated by Django 2.2 on 2020-07-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_delete_tripmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='timezone.now()'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
