# Generated by Django 2.2 on 2020-07-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20200725_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
    ]
